package com.loldle.constants;

import java.util.AbstractMap;
import java.util.Map;

import com.loldle.Champion;
import com.loldle.champion.*;

public final class LoldleArchive
{
    private LoldleArchive()
    {
    }
    
    public static final Map<Integer, Champion> LOLDLE_ARCHIVE = Map.ofEntries(
            new AbstractMap.SimpleEntry<>(121, new BelVeth()),
            new AbstractMap.SimpleEntry<>(120, new Sylas()),
            new AbstractMap.SimpleEntry<>(119, new Taric()),
            new AbstractMap.SimpleEntry<>(118, new Ziggs()),
            new AbstractMap.SimpleEntry<>(117, new Renekton()),
            new AbstractMap.SimpleEntry<>(116, new Sona()),
            new AbstractMap.SimpleEntry<>(115, new Nidalee()),
            new AbstractMap.SimpleEntry<>(114, new Fiddlesticks()),
            new AbstractMap.SimpleEntry<>(113, new Aatrox()),
            new AbstractMap.SimpleEntry<>(112, new Blitzcrank()),
            new AbstractMap.SimpleEntry<>(111, new Morgana()),
            new AbstractMap.SimpleEntry<>(110, new Irelia()),
            new AbstractMap.SimpleEntry<>(109, new LeeSin()),
            new AbstractMap.SimpleEntry<>(108, new Shaco()),
            new AbstractMap.SimpleEntry<>(107, new Pantheon()),
            new AbstractMap.SimpleEntry<>(106, new Kassadin()),
            new AbstractMap.SimpleEntry<>(105, new Malzahar()),
            new AbstractMap.SimpleEntry<>(104, new Ekko()),
            new AbstractMap.SimpleEntry<>(103, new TahmKench()),
            new AbstractMap.SimpleEntry<>(102, new Leona()),
            new AbstractMap.SimpleEntry<>(101, new Cassiopeia()),
            new AbstractMap.SimpleEntry<>(100, new Alistar()),
            new AbstractMap.SimpleEntry<>(99, new Jinx()),
            new AbstractMap.SimpleEntry<>(98, new Elise()),
            new AbstractMap.SimpleEntry<>(97, new Mordekaiser()),
            new AbstractMap.SimpleEntry<>(96, new Nilah()),
            new AbstractMap.SimpleEntry<>(95, new Tryndamere()),
            new AbstractMap.SimpleEntry<>(94, new Ryze()),
            new AbstractMap.SimpleEntry<>(93, new Kennen()),
            new AbstractMap.SimpleEntry<>(92, new Braum()),
            new AbstractMap.SimpleEntry<>(91, new Shen()),
            new AbstractMap.SimpleEntry<>(90, new Tristana()),
            new AbstractMap.SimpleEntry<>(89, new Varus()),
            new AbstractMap.SimpleEntry<>(88, new Evelynn()),
            new AbstractMap.SimpleEntry<>(87, new Urgot()), //Oct 2nd
            new AbstractMap.SimpleEntry<>(86, new Lux()),
            new AbstractMap.SimpleEntry<>(85, new Lillia()),
            new AbstractMap.SimpleEntry<>(84, new TwistedFate()),
            new AbstractMap.SimpleEntry<>(83, new Gragas()),
            new AbstractMap.SimpleEntry<>(82, new Zoe()),
            new AbstractMap.SimpleEntry<>(81, new Volibear()),
            new AbstractMap.SimpleEntry<>(80, new Katarina()),
            new AbstractMap.SimpleEntry<>(79, new Vayne()),
            new AbstractMap.SimpleEntry<>(78, new Rumble()),
            new AbstractMap.SimpleEntry<>(77, new Quinn()),
            new AbstractMap.SimpleEntry<>(76, new Senna()),
            new AbstractMap.SimpleEntry<>(75, new Caitlyn()),
            new AbstractMap.SimpleEntry<>(74, new Vladamir()),
            new AbstractMap.SimpleEntry<>(73, new Neeko()),
            new AbstractMap.SimpleEntry<>(72, new Graves()),
            new AbstractMap.SimpleEntry<>(71, new Draven()),
            new AbstractMap.SimpleEntry<>(70, new Zyra()),
            new AbstractMap.SimpleEntry<>(69, new Kindred()),
            new AbstractMap.SimpleEntry<>(68, new Ahri()),
            new AbstractMap.SimpleEntry<>(67, new Fiora()),
            new AbstractMap.SimpleEntry<>(66, new Seraphine()),
            new AbstractMap.SimpleEntry<>(65, new Gwen()),
            new AbstractMap.SimpleEntry<>(64, new Wukong()),
            new AbstractMap.SimpleEntry<>(63, new Syndra()),
            new AbstractMap.SimpleEntry<>(62, new Gnar()),
            new AbstractMap.SimpleEntry<>(61, new Yorick()),
            new AbstractMap.SimpleEntry<>(60, new Garen()),
            new AbstractMap.SimpleEntry<>(59, new Samira()),
            new AbstractMap.SimpleEntry<>(58, new Galio()),
            new AbstractMap.SimpleEntry<>(57, new Veigar()),
            new AbstractMap.SimpleEntry<>(56, new Janna()),
            new AbstractMap.SimpleEntry<>(55, new Aphelios()),
            new AbstractMap.SimpleEntry<>(54, new Velkoz()),
            new AbstractMap.SimpleEntry<>(53, new Nami()),
            new AbstractMap.SimpleEntry<>(52, new MasterYi()),
            new AbstractMap.SimpleEntry<>(51, new Corki()),
            new AbstractMap.SimpleEntry<>(50, new Lucian()),
            new AbstractMap.SimpleEntry<>(49, new Zilean()),
            new AbstractMap.SimpleEntry<>(48, new Maokai()),
            new AbstractMap.SimpleEntry<>(47, new Xayah()),
            new AbstractMap.SimpleEntry<>(46, new Jhin()),
            new AbstractMap.SimpleEntry<>(45, new Udyr()),
            new AbstractMap.SimpleEntry<>(44, new Zac()),
            new AbstractMap.SimpleEntry<>(43, new RenataGlasc()),
            new AbstractMap.SimpleEntry<>(42, new Sion()),
            new AbstractMap.SimpleEntry<>(41, new Soraka()),
            new AbstractMap.SimpleEntry<>(40, new Nasus()),
            new AbstractMap.SimpleEntry<>(39, new Yuumi()),
            new AbstractMap.SimpleEntry<>(38, new Thresh()),
            new AbstractMap.SimpleEntry<>(37, new Kalista()),
            new AbstractMap.SimpleEntry<>(36, new Chogath()),
            new AbstractMap.SimpleEntry<>(35, new Rakan()),
            new AbstractMap.SimpleEntry<>(34, new Hecarim()),
            new AbstractMap.SimpleEntry<>(33, new Yasuo()),
            new AbstractMap.SimpleEntry<>(32, new Karma()),
            new AbstractMap.SimpleEntry<>(31, new Pyke()),
            new AbstractMap.SimpleEntry<>(30, new DrMundo()),
            new AbstractMap.SimpleEntry<>(29, new Jayce()),
            new AbstractMap.SimpleEntry<>(28, new Ezreal()),
            new AbstractMap.SimpleEntry<>(27, new Rell()),
            new AbstractMap.SimpleEntry<>(26, new Twitch()),
            new AbstractMap.SimpleEntry<>(25, new Kayn()),
            new AbstractMap.SimpleEntry<>(24, new Khazix()),
            new AbstractMap.SimpleEntry<>(23, new Akshan()),
            new AbstractMap.SimpleEntry<>(22, new XinZhao()),
            new AbstractMap.SimpleEntry<>(21, new Ornn()),
            new AbstractMap.SimpleEntry<>(20, new Viego()),
            new AbstractMap.SimpleEntry<>(19, new Warwick()),
            new AbstractMap.SimpleEntry<>(18, new Zeri()),
            new AbstractMap.SimpleEntry<>(17, new Olaf()),
            new AbstractMap.SimpleEntry<>(16, new Vex()),
            new AbstractMap.SimpleEntry<>(15, new Amumu()),
            new AbstractMap.SimpleEntry<>(14, new Karthus()),
            new AbstractMap.SimpleEntry<>(13, new Ivern()),
            new AbstractMap.SimpleEntry<>(12, new Kled()),
            new AbstractMap.SimpleEntry<>(11, new Aatrox()),
            new AbstractMap.SimpleEntry<>(10, new Kayle()),
            new AbstractMap.SimpleEntry<>(9, new Irelia()),
            new AbstractMap.SimpleEntry<>(8, new Nunu()),
            new AbstractMap.SimpleEntry<>(7, new Fiddlesticks())
//            new AbstractMap.SimpleEntry<>(6, null),
//            new AbstractMap.SimpleEntry<>(5, null),
//            new AbstractMap.SimpleEntry<>(4, null),
//            new AbstractMap.SimpleEntry<>(3, null),
//            new AbstractMap.SimpleEntry<>(2, null),
//            new AbstractMap.SimpleEntry<>(1, null)
            );
}
